# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  JF_HOST: "psazuse.jfrog.io"
  JFROG_RT_USER: "${env:USER_NAME}"
  JFROG_CLI_LOG_LEVEL: "DEBUG"
  JF_ACCESS_TOKEN: "${env:ACCESS_TOKEN}"
  JF_RT_URL: "https://${JF_HOST}"
  RT_REPO_VIRTUAL: "krishnam-mvn-virtual"

steps:
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'jfrog-ps'
    command: 'jf rt ping'

