# This workflow will fecth code on weekly from and sync with my repo

name: "Sync from Forked repo"
on:
  schedule: # cron time is UTC 
    # - cron: "0 0 * * SAT" #  Runs on Every Sat at 2pm PT. Refer https://crontab.guru/every-saturday
permissions:
  actions: read # for detecting the Github Actions environment.
jobs:
  syncRepo:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    env:
      FORKED_REPO: "spring-projects/spring-petclinic" # https://github.com/spring-projects/spring-petclinic
      FORKED_REPO_PATH: "forked-spring-petclinic"
      FORKED_REPO_BRANCH : "main"
      MY_REPO: "krishnamanchikalapudi/spring-petclinic"
      MY_REPO_PATH: "my-spring-petclinic"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20   # ref  https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
    steps:
      - name: Checkout Forked-repo ${{ env.FORKED_REPO }}
        uses: actions/checkout@v4 # ref: https://github.com/actions/checkout
        with:
          repository: ${{ env.FORKED_REPO }}
          token: ${{ github.token }}
          ref: ${{ env.FORKED_REPO_BRANCH }}
          path: ${{ env.FORKED_REPO_PATH }}

      - name: Checkout my-repo ${{ env.MY_REPO }}
        uses: actions/checkout@v4 
        with:
          repository: ${{ env.MY_REPO }}
          path: ${{ env.MY_REPO_PATH }}

      - name: list folders
        run: |
          pwd
          ls -lrt .

          echo "\n\n * Repo: ${{ env.FORKED_REPO_PATH }} \n"
          ls -lrt ${{ env.FORKED_REPO_PATH }} 

          echo "\n\n * Repo: ${{ env.MY_REPO_PATH }} \n"
          ls -lrt ${{ env.MY_REPO_PATH }}

      - name: Clean my-repo folders
        run: |
          cd ${{ env.MY_REPO_PATH }}
          pwd
          ls -lrta .

          echo "\n\n * Deleting files \n"
          rm -rf src/ target/ k8s/ .gradle/ .mvn/
          ls -lrta .

      - name: Copy files from ${{ env.FORKED_REPO_PATH }} to ${{ env.MY_REPO_PATH }}
        run: |
          cd ${{ env.MY_REPO_PATH }}
          pwd
          ls -lrta .

          echo "\n\n * Copying files from ${{ env.FORKED_REPO_PATH }} to ${{ env.MY_REPO_PATH }} \n"
          cp -R -f ../${{ env.FORKED_REPO_PATH }}/* .
          ls -lrta .

      - name: Commit files to GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: ${{ github.actor }}
        run: |
          cd ${{ env.MY_REPO_PATH }}
          ls -lrta .
          echo "\n\n * Commiting files, branch: main of my repo ${{ env.MY_REPO }} with actor: ${GH_USER} "

          git config --global user.email "${GH_USER}@gmail.com"
          git config --global user.name "${GH_USER}"

          git add . -v 
          git commit -m "Sync on $(date +'%Y-%m-%d') from parent repo"
          git push -v https://${GH_USER}:${GH_TOKEN}@github.com/${{ env.MY_REPO }}.git ${{env.FORKED_REPO_BRANCH}}

      - name: summary
        run: |
          echo "# :copyright: Summary :adhesive_bandage:" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " - Forked code from ${{ env.FORKED_REPO }} " >> $GITHUB_STEP_SUMMARY
          echo " - My repo code ${{ env.MY_REPO }} " >> $GITHUB_STEP_SUMMARY
          
